openapi: 3.0.0
info:
  title: NexusLink Call Center API
  description: API for managing call center data and customer interactions
  version: 1.0.0
  contact:
    name: NexusLink Support
    email: support@nexuslink.com

servers:
  - url: https://nexuslink-api.onrender.com
    description: Production server

paths:
  /:
    get:
      summary: Health check endpoint
      operationId: healthCheck
      responses:
        '200':
          description: API status
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  version:
                    type: string
                  status:
                    type: string

  /calls:
    get:
      summary: Get all calls
      description: Retrieve all customer service calls
      operationId: getAllCalls
      responses:
        '200':
          description: List of all calls
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  data:
                    type: object
                  total:
                    type: integer
    
    post:
      summary: Create new call record
      description: |
        Create a new customer service call record with complete information.
        
        **🚨 CRITICAL: ALL 5 fields below are MANDATORY and must be collected before making the API call:**
        
        1. **Call** - Call identifier (e.g., "llamada 15") - REQUIRED
        2. **Client** - Client ID or phone number - REQUIRED  
        3. **Operator** - Full name of the operator - REQUIRED
        4. **Conversation** - Complete conversation transcript - REQUIRED
        5. **Correo** - Client's email address - REQUIRED (needed for surveys and follow-up)
        
        ⚠️ The API will return a 400 error if ANY of these fields is missing or empty.
        
        📧 The email field (Correo) is especially important as it's used for sending satisfaction surveys.
      operationId: createCall
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - Call
                - Client
                - Operator
                - Conversation
                - Correo
              properties:
                Call:
                  type: string
                  description: "🔢 **REQUIRED FIELD #1** - Call identifier or call number (e.g., 'llamada 15', 'llamada 20')"
                  example: "llamada 15"
                Client:
                  type: string
                  description: "👤 **REQUIRED FIELD #2** - Client ID, phone number, or client identifier"
                  example: "62351441"
                Operator:
                  type: string
                  description: "🧑‍💼 **REQUIRED FIELD #3** - Full name of the operator handling the call"
                  example: "Jesus Madero"
                Conversation:
                  type: string
                  description: "💬 **REQUIRED FIELD #4** - Complete conversation transcript between operator and client"
                  example: "Operador: Buenos días, me comunico de soporte técnico. Cliente: Hola, tengo problemas con internet..."
                Correo:
                  type: string
                  format: email
                  description: "📧 **REQUIRED FIELD #5** - Client's email address (MANDATORY for sending follow-up surveys and communications)"
                  example: "cliente@email.com"
      responses:
        '201':
          description: Call created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: "Call created successfully"
                  call_id:
                    type: string
                    example: "call_1234567890"
                  data:
                    type: object
                    description: The created call record
                  summary:
                    type: object
                    properties:
                      call_name:
                        type: string
                      client_id:
                        type: string
                      operator:
                        type: string
                      email:
                        type: string
                      conversation_length:
                        type: integer
                      date_created:
                        type: string
        '400':
          description: Missing required fields or invalid data
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  error:
                    type: string
                    example: "Missing required fields. Please provide all the following information:"
                  missing_fields:
                    type: array
                    items:
                      type: string
                    example: ["Call - Call identifier", "Correo - Client email address"]
                  required_fields:
                    type: array
                    items:
                      type: string
                    example: ["Call", "Client", "Operator", "Conversation", "Correo"]
                  example:
                    type: object
                    properties:
                      Call:
                        type: string
                        example: "llamada 15"
                      Client:
                        type: string
                        example: "62351441"
                      Operator:
                        type: string
                        example: "Jesus Madero"
                      Conversation:
                        type: string
                        example: "Operador: Buenos días..."
                      Correo:
                        type: string
                        example: "cliente@email.com"

  /calls/format:
    get:
      summary: Get call creation format
      description: Returns the required format and fields for creating a new call
      operationId: getCallFormat
      responses:
        '200':
          description: Call format requirements
          content:
            application/json:
              schema:
                type: object
                properties:
                  required_fields:
                    type: object
                    additionalProperties:
                      type: object
                      properties:
                        description:
                          type: string
                        example:
                          type: string
                        required:
                          type: boolean
                  example_request:
                    type: object
                    properties:
                      Call:
                        type: string
                        example: "llamada 15"
                      Client:
                        type: string
                        example: "62351441"
                      Operator:
                        type: string
                        example: "Jesus Madero"
                      Conversation:
                        type: string
                        example: "Operador: Buenos días..."
                      Correo:
                        type: string
                        example: "silvia.trejor@uanl.edu.mx"

  /calls/{call_id}:
    get:
      summary: Get call by ID
      description: Retrieve a specific call by its ID
      operationId: getCallById
      parameters:
        - name: call_id
          in: path
          required: true
          schema:
            type: string
          description: Unique call identifier
      responses:
        '200':
          description: Call details
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  data:
                    type: object
        '404':
          description: Call not found
    
    put:
      summary: Update call
      description: Update an existing call record
      operationId: updateCall
      parameters:
        - name: call_id
          in: path
          required: true
          schema:
            type: string
          description: Unique call identifier
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                Call:
                  type: string
                  description: Call identifier
                Operator:
                  type: string
                  description: Operator name
                Client:
                  type: string
                  description: Client ID
                Conversation:
                  type: string
                  description: Conversation transcript
                Correo:
                  type: string
                  format: email
                  description: Client email
      responses:
        '200':
          description: Call updated successfully

  /calls/search:
    get:
      summary: Search calls
      description: Search calls by client or operator
      operationId: searchCalls
      parameters:
        - name: client
          in: query
          schema:
            type: string
          description: Client name to search for
        - name: operator
          in: query
          schema:
            type: string
          description: Operator name to search for
      responses:
        '200':
          description: Search results
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  data:
                    type: object
                  total:
                    type: integer

  /analytics/summary:
    get:
      summary: Get analytics summary
      description: Get summary statistics of all calls
      operationId: getAnalyticsSummary
      responses:
        '200':
          description: Analytics summary
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  total_calls:
                    type: integer
                  total_operators:
                    type: integer
                  total_clients:
                    type: integer
                  operators:
                    type: array
                    items:
                      type: string
                  clients:
                    type: array
                    items:
                      type: string
                      
  /calls/{call_id}/send-survey:
    post:
      summary: Send satisfaction survey
      description: Send customer satisfaction survey via email for a specific call
      operationId: sendSatisfactionSurvey
      parameters:
        - name: call_id
          in: path
          required: true
          schema:
            type: string
          description: Call ID to send survey for
      responses:
        '200':
          description: Survey sent successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                  survey_id:
                    type: string
                  sent_to:
                    type: string
                  client_id:
                    type: string
        '400':
          description: No email found or survey already sent
        '404':
          description: Call not found

  /surveys/stats:
    get:
      summary: Get survey statistics
      description: Get statistics about sent satisfaction surveys
      operationId: getSurveyStats
      responses:
        '200':
          description: Survey statistics
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  stats:
                    type: object
                    properties:
                      total_sent:
                        type: integer
                      by_operator:
                        type: object
                      recent_surveys:
                        type: array
                      today_count:
                        type: integer

  /surveys:
    get:
      summary: List all surveys
      description: Get list of all sent surveys
      operationId: getAllSurveys
      responses:
        '200':
          description: List of surveys
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  surveys:
                    type: array
                  total:
                    type: integer
  

components:
  schemas:
    Call:
      type: object
      properties:
        Call:
          type: string
          description: Call identifier
          example: "llamada 15"
        Operator:
          type: string
          description: Operator name
          example: "Jesus Madero"
        Client:
          type: string
          description: Client ID or phone number
          example: "62351441"
        Date:
          type: string
          description: Call date
          example: "2025-03-12"
        Conversation:
          type: string
          description: Complete conversation transcript
          example: "Operador: Buenos días, me comunico de soporte técnico..."
        Correo:
          type: string
          format: email
          description: Client email address
          example: "silvia.trejor@uanl.edu.mx"
        CreatedAt:
          type: string
          format: date-time
          description: Timestamp when call was created
        UpdatedAt:
          type: string
          format: date-time
          description: Timestamp when call was last updated